// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btwhehspuszevbqpogpi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0d2hlaHNwdXN6ZXZicXBvZ3BpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5MDI2MjIsImV4cCI6MjA3MTQ3ODYyMn0.46jDPxUd8mFVjWbjPw3OqkNf2B5vrZZnLWXy_Y1SdM4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});